CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "DiagnosticRules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Conditions" text NOT NULL,
    "LogicType" text NOT NULL,
    "Confidence" double precision NOT NULL,
    "Conclusion" text NOT NULL,
    "Description" text NOT NULL,
    "Priority" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_DiagnosticRules" PRIMARY KEY ("Id")
);

CREATE TABLE "Garages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "City" text NOT NULL,
    "Address" text NOT NULL,
    "PhoneNumber" text NOT NULL,
    "GarageType" text NOT NULL,
    "EvSupported" boolean NOT NULL,
    "Rating" double precision NOT NULL,
    "OperatingHours" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_Garages" PRIMARY KEY ("Id")
);

CREATE TABLE "ImageDiagnostics" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VisualFeature" text NOT NULL,
    "Confidence" double precision NOT NULL,
    "LikelyIssue" text NOT NULL,
    "Urgency" text NOT NULL,
    "FilePath" text NOT NULL,
    "ImageType" text NOT NULL,
    "Description" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_ImageDiagnostics" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "PhoneNumber" text NOT NULL,
    "City" text NOT NULL,
    "FamilyType" text NOT NULL,
    "ExperienceLevel" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "VehicleIssues" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Symptom" text NOT NULL,
    "AffectedSystem" text NOT NULL,
    "Severity" text NOT NULL,
    "DrivesSafe" boolean NOT NULL,
    "Description" text NOT NULL,
    "PossibleCauses" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_VehicleIssues" PRIMARY KEY ("Id")
);

CREATE TABLE "Services" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GarageId" integer NOT NULL,
    "ServiceName" text NOT NULL,
    "Category" text NOT NULL,
    "AvgCostAed" numeric NOT NULL,
    "SkillLevel" text NOT NULL,
    "Description" text NOT NULL,
    "EstimatedDurationMinutes" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_Services" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Services_Garages_GarageId" FOREIGN KEY ("GarageId") REFERENCES "Garages" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Vehicles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Brand" text NOT NULL,
    "Model" text NOT NULL,
    "Year" integer NOT NULL,
    "VehicleType" text NOT NULL,
    "FuelType" text NOT NULL,
    "Color" text NOT NULL,
    "MileageKm" double precision NOT NULL,
    "LicensePlate" text NOT NULL,
    "City" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_Vehicles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Vehicles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ServiceHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VehicleId" integer NOT NULL,
    "GarageId" integer NOT NULL,
    "ServiceId" integer NOT NULL,
    "ServiceDate" timestamp with time zone NOT NULL,
    "MileageKm" double precision NOT NULL,
    "CostAed" numeric NOT NULL,
    "Outcome" text NOT NULL,
    "Notes" text NOT NULL,
    "TechnicianId" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" text,
    CONSTRAINT "PK_ServiceHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ServiceHistories_Garages_GarageId" FOREIGN KEY ("GarageId") REFERENCES "Garages" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ServiceHistories_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ServiceHistories_Vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES "Vehicles" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_DiagnosticRule_LogicType" ON "DiagnosticRules" ("LogicType");

CREATE INDEX "IX_Garages_Name_City_Type" ON "Garages" ("Name", "City", "GarageType");

CREATE INDEX "IX_ImageDiagnostic_Urgency" ON "ImageDiagnostics" ("Urgency");

CREATE INDEX "IX_ServiceHistories_ServiceId" ON "ServiceHistories" ("ServiceId");

CREATE INDEX "IX_ServiceHistory_GarageId" ON "ServiceHistories" ("GarageId");

CREATE INDEX "IX_ServiceHistory_ServiceDate" ON "ServiceHistories" ("ServiceDate");

CREATE INDEX "IX_ServiceHistory_VehicleId" ON "ServiceHistories" ("VehicleId");

CREATE INDEX "IX_Services_Category" ON "Services" ("Category");

CREATE INDEX "IX_Services_GarageId" ON "Services" ("GarageId");

CREATE INDEX "IX_Users_Name_Email" ON "Users" ("Name", "Email");

CREATE INDEX "IX_VehicleIssue_Severity" ON "VehicleIssues" ("Severity");

CREATE INDEX "IX_Vehicles_Brand_Model_City" ON "Vehicles" ("Brand", "Model", "City");

CREATE INDEX "IX_Vehicles_UserId" ON "Vehicles" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260111090151_InitialCreate', '10.0.1');

COMMIT;

